---
# This playbook will install mysql and create db user and give permissions.

- name: Prepare to install MySQL Server
  shell: wget https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
  ignore_errors: yes

- name: Install repo for mysql server
  shell: sudo rpm -ivh mysql57-community-release-el7-9.noarch.rpm
  ignore_errors: yes

- name: Install Mysql package
  yum: name={{ item }} state=installed
  with_items:
   - mysql-server
   - MySQL-python
   - libselinux-python
   - libsemanage-python

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: sestatus.rc != 0

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes

- name: insert iptables rule
  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}"
              insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
  notify: restart iptables